# .github/workflows/release-push.yml
name: Build and Push Release Image

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag version
        id: get_tag_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Containerfile
          platforms: linux/amd64
          build-args: |
            FRAPPE_PATH=https://github.com/frappe/frappe
            FRAPPE_BRANCH=version-15
            APPS_JSON_BASE64=${{ secrets.APPS_JSON_BASE64_CONTENT }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ steps.get_tag_version.outputs.VERSION }}
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          push: true # Push the image to GHCR
